/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salman.s;

import grph.Grph;
import grph.in_memory.InMemoryGrph;
import grph.properties.NumericalProperty;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.PriorityQueue;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author megarokr
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_ingredientes = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        p_agregarIngrediente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombreIngrediente = new javax.swing.JTextField();
        jc_tipoMedida = new javax.swing.JComboBox();
        jsp_cantidad = new javax.swing.JSpinner();
        jc_unidadMedida = new javax.swing.JComboBox();
        jc_cargarExistente = new javax.swing.JComboBox();
        cmd_agregarAlmacen = new javax.swing.JButton();
        p_eliminarIngrediente = new javax.swing.JPanel();
        jc_eliminarIngrediente = new javax.swing.JComboBox();
        cmd_eliminarIngrediente = new javax.swing.JButton();
        jd_platos = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        p_agregarIngrediente1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombreIngredientePlato = new javax.swing.JTextField();
        jc_tipoMedidaPlato = new javax.swing.JComboBox();
        jsp_cantidadPlato = new javax.swing.JSpinner();
        jc_unidadMedidaPlato = new javax.swing.JComboBox();
        jc_cargarExistentePlato = new javax.swing.JComboBox();
        cmd_agregarLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_ingredientesPlato = new javax.swing.JList();
        jLabel11 = new javax.swing.JLabel();
        tf_nombrePlato = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jsp_precioPlato = new javax.swing.JSpinner();
        jsp_tiempo = new javax.swing.JSpinner();
        cmd_agregarPlato = new javax.swing.JButton();
        p_agregarIngrediente2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_nombreIngredientePlato1 = new javax.swing.JTextField();
        jc_tipoMedidaPlato1 = new javax.swing.JComboBox();
        jsp_cantidadPlato1 = new javax.swing.JSpinner();
        jc_unidadMedidaPlato1 = new javax.swing.JComboBox();
        jc_cargarExistentePlato1 = new javax.swing.JComboBox();
        cmd_agregarLista1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_ingredientesPlato1 = new javax.swing.JList();
        jLabel19 = new javax.swing.JLabel();
        tf_nombrePlato1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jsp_precioPlato1 = new javax.swing.JSpinner();
        jsp_tiempo1 = new javax.swing.JSpinner();
        cmd_agregarPlato1 = new javax.swing.JButton();
        jc_cargarPlato = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jc_eliminarPlato = new javax.swing.JComboBox();
        cmd_eliminarPlato = new javax.swing.JButton();
        jd_ordenes = new javax.swing.JDialog();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jsp_vertex = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jc_from = new javax.swing.JComboBox();
        jc_to = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jsp_peso = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        isDrigida = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jc_menu = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_platosOrden = new javax.swing.JList();
        btn_add = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf_cliente = new javax.swing.JTextField();
        jc_dirección = new javax.swing.JComboBox();
        jd_cocina = new javax.swing.JDialog();
        jd_cierre = new javax.swing.JDialog();
        jl_icon = new javax.swing.JLabel();
        cmd_ingredientes = new javax.swing.JButton();
        cmd_platos = new javax.swing.JButton();
        cmd_ordenes = new javax.swing.JButton();
        cmd_cocina = new javax.swing.JButton();
        cmd_cierre = new javax.swing.JButton();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Tipo de medición:");

        jLabel3.setText("Cantidad:");

        jLabel4.setText("Unidad:");

        jLabel5.setText("Cargar existente:");

        jc_tipoMedida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Volumen", "Masa", "Unidad" }));
        jc_tipoMedida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_tipoMedidaItemStateChanged(evt);
            }
        });

        jsp_cantidad.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.5d), Double.valueOf(0.5d), null, Double.valueOf(0.5d)));

        jc_cargarExistente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_cargarExistenteItemStateChanged(evt);
            }
        });

        cmd_agregarAlmacen.setText("Agregar");
        cmd_agregarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_agregarAlmacenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_agregarIngredienteLayout = new javax.swing.GroupLayout(p_agregarIngrediente);
        p_agregarIngrediente.setLayout(p_agregarIngredienteLayout);
        p_agregarIngredienteLayout.setHorizontalGroup(
            p_agregarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_agregarIngredienteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(p_agregarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_agregarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombreIngrediente)
                    .addComponent(jc_tipoMedida, 0, 150, Short.MAX_VALUE)
                    .addComponent(jsp_cantidad)
                    .addComponent(jc_unidadMedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(p_agregarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jc_cargarExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(p_agregarIngredienteLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(cmd_agregarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_agregarIngredienteLayout.setVerticalGroup(
            p_agregarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_agregarIngredienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(p_agregarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(tf_nombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jc_tipoMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_cargarExistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jsp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jc_unidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(cmd_agregarAlmacen)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", p_agregarIngrediente);

        cmd_eliminarIngrediente.setText("Eliminar");
        cmd_eliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_eliminarIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_eliminarIngredienteLayout = new javax.swing.GroupLayout(p_eliminarIngrediente);
        p_eliminarIngrediente.setLayout(p_eliminarIngredienteLayout);
        p_eliminarIngredienteLayout.setHorizontalGroup(
            p_eliminarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_eliminarIngredienteLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jc_eliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(cmd_eliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        p_eliminarIngredienteLayout.setVerticalGroup(
            p_eliminarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_eliminarIngredienteLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(p_eliminarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_eliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_eliminarIngrediente))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", p_eliminarIngrediente);

        javax.swing.GroupLayout jd_ingredientesLayout = new javax.swing.GroupLayout(jd_ingredientes.getContentPane());
        jd_ingredientes.getContentPane().setLayout(jd_ingredientesLayout);
        jd_ingredientesLayout.setHorizontalGroup(
            jd_ingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jd_ingredientesLayout.setVerticalGroup(
            jd_ingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jLabel6.setText("Nombre:");

        jLabel7.setText("Tipo de medición:");

        jLabel8.setText("Cantidad:");

        jLabel9.setText("Unidad:");

        jLabel10.setText("Cargar existente:");

        jc_tipoMedidaPlato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Volumen", "Masa", "Unidad" }));
        jc_tipoMedidaPlato.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_tipoMedidaPlatoItemStateChanged(evt);
            }
        });

        jsp_cantidadPlato.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.5d), Double.valueOf(0.5d), null, Double.valueOf(0.5d)));

        jc_cargarExistentePlato.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_cargarExistentePlatoItemStateChanged(evt);
            }
        });

        cmd_agregarLista.setText("Agregar Ingrediente");
        cmd_agregarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_agregarListaActionPerformed(evt);
            }
        });

        jl_ingredientesPlato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_ingredientesPlatoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jl_ingredientesPlato);

        jLabel11.setText("Nombre plato:");

        jLabel12.setText("Precio:");

        jLabel13.setText("Cocción:");

        jsp_precioPlato.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(1.0d), null, Double.valueOf(0.5d)));

        jsp_tiempo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        cmd_agregarPlato.setText("Agregar Plato");
        cmd_agregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_agregarPlatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_agregarIngrediente1Layout = new javax.swing.GroupLayout(p_agregarIngrediente1);
        p_agregarIngrediente1.setLayout(p_agregarIngrediente1Layout);
        p_agregarIngrediente1Layout.setHorizontalGroup(
            p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_agregarIngrediente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmd_agregarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(p_agregarIngrediente1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_agregarIngrediente1Layout.createSequentialGroup()
                        .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreIngredientePlato)
                            .addComponent(jc_tipoMedidaPlato, 0, 150, Short.MAX_VALUE)
                            .addComponent(jsp_cantidadPlato)
                            .addComponent(jc_unidadMedidaPlato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jc_cargarExistentePlato, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(p_agregarIngrediente1Layout.createSequentialGroup()
                        .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmd_agregarPlato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_agregarIngrediente1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jsp_precioPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jsp_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        p_agregarIngrediente1Layout.setVerticalGroup(
            p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_agregarIngrediente1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(tf_nombreIngredientePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jc_tipoMedidaPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_cargarExistentePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jsp_cantidadPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jc_unidadMedidaPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmd_agregarLista)
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addGroup(p_agregarIngrediente1Layout.createSequentialGroup()
                        .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_nombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jsp_precioPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p_agregarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jsp_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(cmd_agregarPlato)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Agregar", p_agregarIngrediente1);

        jLabel14.setText("Nombre:");

        jLabel15.setText("Tipo de medición:");

        jLabel16.setText("Cantidad:");

        jLabel17.setText("Unidad:");

        jLabel18.setText("Cargar existente:");

        jc_tipoMedidaPlato1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Volumen", "Masa", "Unidad" }));
        jc_tipoMedidaPlato1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_tipoMedidaPlato1ItemStateChanged(evt);
            }
        });

        jsp_cantidadPlato1.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.5d), Double.valueOf(0.5d), null, Double.valueOf(0.5d)));

        jc_cargarExistentePlato1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_cargarExistentePlato1ItemStateChanged(evt);
            }
        });

        cmd_agregarLista1.setText("Agregar Ingrediente");
        cmd_agregarLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_agregarLista1ActionPerformed(evt);
            }
        });

        jl_ingredientesPlato1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_ingredientesPlato1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jl_ingredientesPlato1);

        jLabel19.setText("Nombre plato:");

        jLabel20.setText("Precio:");

        jLabel21.setText("Cocción:");

        jsp_precioPlato1.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(1.0d), null, Double.valueOf(0.5d)));

        jsp_tiempo1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        cmd_agregarPlato1.setText("Agregar Plato");
        cmd_agregarPlato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_agregarPlato1ActionPerformed(evt);
            }
        });

        jc_cargarPlato.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_cargarPlatoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout p_agregarIngrediente2Layout = new javax.swing.GroupLayout(p_agregarIngrediente2);
        p_agregarIngrediente2.setLayout(p_agregarIngrediente2Layout);
        p_agregarIngrediente2Layout.setHorizontalGroup(
            p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_agregarIngrediente2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmd_agregarLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(p_agregarIngrediente2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_agregarIngrediente2Layout.createSequentialGroup()
                        .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreIngredientePlato1)
                            .addComponent(jc_tipoMedidaPlato1, 0, 150, Short.MAX_VALUE)
                            .addComponent(jsp_cantidadPlato1)
                            .addComponent(jc_unidadMedidaPlato1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addComponent(jc_cargarExistentePlato1, 0, 202, Short.MAX_VALUE)
                            .addComponent(jc_cargarPlato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(p_agregarIngrediente2Layout.createSequentialGroup()
                        .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmd_agregarPlato1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_agregarIngrediente2Layout.createSequentialGroup()
                                .addGap(0, 98, Short.MAX_VALUE)
                                .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jsp_precioPlato1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombrePlato1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jsp_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        p_agregarIngrediente2Layout.setVerticalGroup(
            p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_agregarIngrediente2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(tf_nombreIngredientePlato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jc_tipoMedidaPlato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_cargarExistentePlato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jsp_cantidadPlato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_cargarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jc_unidadMedidaPlato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmd_agregarLista1)
                .addGap(18, 18, 18)
                .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addGroup(p_agregarIngrediente2Layout.createSequentialGroup()
                        .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tf_nombrePlato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jsp_precioPlato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p_agregarIngrediente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jsp_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(cmd_agregarPlato1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Modificar", p_agregarIngrediente2);

        cmd_eliminarPlato.setText("Eliminar");
        cmd_eliminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_eliminarPlatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jc_eliminarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(cmd_eliminarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_eliminarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_eliminarPlato))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar", jPanel1);

        javax.swing.GroupLayout jd_platosLayout = new javax.swing.GroupLayout(jd_platos.getContentPane());
        jd_platos.getContentPane().setLayout(jd_platosLayout);
        jd_platosLayout.setHorizontalGroup(
            jd_platosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_platosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jd_platosLayout.setVerticalGroup(
            jd_platosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_platosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jLabel22.setText("Número de vértices:");

        jsp_vertex.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jButton1.setText("Crear Grafo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel23.setText("Aristas");

        jLabel24.setText("peso:");

        isDrigida.setText("Dirigida");

        jButton2.setText("Crear arista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(100, 100, 100)
                                        .addComponent(jsp_peso))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jsp_vertex, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(isDrigida))))
                            .addComponent(jLabel25)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jc_from, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jc_to, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton2)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jsp_vertex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jsp_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isDrigida))
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Armar Grafo", jPanel3);

        jl_platosOrden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_platosOrdenKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jl_platosOrden);

        btn_add.setText("Añadir");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jButton4.setText("Terminar órden");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel26.setText("Nombre cliente:");

        jLabel27.setText("Dirección:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jc_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btn_add))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_cliente)
                                    .addComponent(jc_dirección, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(35, 35, 35)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jc_dirección, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jc_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_add)
                .addGap(55, 55, 55)
                .addComponent(jButton4)
                .addGap(38, 38, 38))
        );

        jTabbedPane3.addTab("Ordenar", jPanel2);

        javax.swing.GroupLayout jd_ordenesLayout = new javax.swing.GroupLayout(jd_ordenes.getContentPane());
        jd_ordenes.getContentPane().setLayout(jd_ordenesLayout);
        jd_ordenesLayout.setHorizontalGroup(
            jd_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ordenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        jd_ordenesLayout.setVerticalGroup(
            jd_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ordenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_cocinaLayout = new javax.swing.GroupLayout(jd_cocina.getContentPane());
        jd_cocina.getContentPane().setLayout(jd_cocinaLayout);
        jd_cocinaLayout.setHorizontalGroup(
            jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_cocinaLayout.setVerticalGroup(
            jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_cierreLayout = new javax.swing.GroupLayout(jd_cierre.getContentPane());
        jd_cierre.getContentPane().setLayout(jd_cierreLayout);
        jd_cierreLayout.setHorizontalGroup(
            jd_cierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_cierreLayout.setVerticalGroup(
            jd_cierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        jl_icon.setIcon(new javax.swing.ImageIcon("/home/megarokr/Salmans/Salman's/images/mw_background.jpg")); // NOI18N

        cmd_ingredientes.setText("Ingredientes");
        cmd_ingredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_ingredientesActionPerformed(evt);
            }
        });

        cmd_platos.setText("Platos");
        cmd_platos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_platosActionPerformed(evt);
            }
        });

        cmd_ordenes.setText("Órdenes");
        cmd_ordenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_ordenesActionPerformed(evt);
            }
        });

        cmd_cocina.setText("Cocina");
        cmd_cocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_cocinaActionPerformed(evt);
            }
        });

        cmd_cierre.setText("Cierre");
        cmd_cierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_cierreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jl_icon)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_ingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(cmd_platos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(cmd_ordenes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cmd_cocina, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmd_cierre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jl_icon)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_ingredientes)
                    .addComponent(cmd_platos)
                    .addComponent(cmd_ordenes)
                    .addComponent(cmd_cocina)
                    .addComponent(cmd_cierre))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_ingredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_ingredientesActionPerformed
        if(!storage.getAlmacen().isEmpty()){
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < storage.getAlmacen().size(); i++) {
                modelo.addElement(storage.getAlmacen().get(i).peek().getName());
            }
            jc_cargarExistente.setModel(modelo);
            jc_eliminarIngrediente.setModel(modelo);
        }        
        openDialog(jd_ingredientes);
    }//GEN-LAST:event_cmd_ingredientesActionPerformed

    private void cmd_platosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_platosActionPerformed
        if(!storage.getAlmacen().isEmpty()){
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < storage.getAlmacen().size(); i++) {
                modelo.addElement(storage.getAlmacen().get(i).peek().getName());
            }
            jc_cargarExistentePlato.setModel(modelo);
            jc_cargarExistentePlato1.setModel(modelo);
        }  
        openDialog(jd_platos);
    }//GEN-LAST:event_cmd_platosActionPerformed

    private void cmd_ordenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_ordenesActionPerformed
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < menu.size(); i++) {
            modelo.addElement(menu.get(i).getNombre());
        }
        openDialog(jd_ordenes);
    }//GEN-LAST:event_cmd_ordenesActionPerformed

    private void cmd_cocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_cocinaActionPerformed
        grafo.display();
    }//GEN-LAST:event_cmd_cocinaActionPerformed

    private void cmd_cierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_cierreActionPerformed
        openDialog(jd_cierre);
    }//GEN-LAST:event_cmd_cierreActionPerformed

    private void jc_tipoMedidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_tipoMedidaItemStateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        //modelo = (DefaultComboBoxModel)jc_unidadMedida.getModel();
        
        String selected = jc_tipoMedida.getSelectedItem().toString();
        if(selected.equalsIgnoreCase("Volumen")){
            modelo.addElement("Litros");
            modelo.addElement("Mililitros");
            modelo.addElement("Galones");
        }
        else if(selected.equalsIgnoreCase("Masa")){
            modelo.addElement("Kilogramos");
            modelo.addElement("Libras");
            modelo.addElement("Onzas");
            modelo.addElement("Gramos");
        }
        else{
            modelo.addElement("Unidades");
        }
        jc_unidadMedida.setModel(modelo);
    }//GEN-LAST:event_jc_tipoMedidaItemStateChanged

    private void cmd_agregarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_agregarAlmacenActionPerformed
        if(tf_nombreIngrediente != null){
            int selec = JOptionPane.showConfirmDialog(jd_ingredientes, "¿Está seguro que desea agregar este ingrediente? Recuerde que no puede modificarse.","Confirmar",JOptionPane.YES_NO_OPTION);
            if(selec == JOptionPane.OK_OPTION){
                String nombre = tf_nombreIngrediente.getText();
                double cantidad = Double.parseDouble(jsp_cantidad.getValue().toString());
                String tipo = jc_tipoMedida.getSelectedItem().toString();
                String unidad = jc_unidadMedida.getSelectedItem().toString();
                
                Ingredient temp = new Ingredient(nombre,cantidad,unidad,tipo);
                storage.addToStorage(temp);
                
                DefaultComboBoxModel modelo = new DefaultComboBoxModel();
                for (int i = 0; i < storage.getAlmacen().size(); i++) {
                    modelo.addElement(storage.getAlmacen().get(i).peek().getName());
                }
                jc_cargarExistente.setModel(modelo);
                jc_eliminarIngrediente.setModel(modelo);
                
                tf_nombreIngrediente.setText("");
                
                JOptionPane.showMessageDialog(jd_ingredientes, "¡Ingrediente agregado con éxito!", "¡Bien hecho!", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(jd_ingredientes, "Nombre vacío", "Campo faltante", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmd_agregarAlmacenActionPerformed

    private void jc_cargarExistenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_cargarExistenteItemStateChanged
        tf_nombreIngrediente.setText(jc_cargarExistente.getSelectedItem().toString());
    }//GEN-LAST:event_jc_cargarExistenteItemStateChanged

    private void cmd_eliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_eliminarIngredienteActionPerformed
        int selec = JOptionPane.showConfirmDialog(jd_ingredientes, "¿Está seguro que desea eliminar este ingrediente?"
                                                   + "Recuerde que se eliminará toda existencia del mismo. Está acción no se puede revertir","Precaución",
                                                   JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(selec == JOptionPane.OK_OPTION){
            storage.getAlmacen().remove(jc_eliminarIngrediente.getSelectedIndex());
            JOptionPane.showMessageDialog(jd_ingredientes, "¡Ingrediente eliminado éxitosamente!", "¡Bien hecho!", JOptionPane.INFORMATION_MESSAGE);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < storage.getAlmacen().size(); i++) {
                modelo.addElement(storage.getAlmacen().get(i).peek().getName());
            }
            jc_cargarExistente.setModel(modelo);
            jc_eliminarIngrediente.setModel(modelo);
        }
    }//GEN-LAST:event_cmd_eliminarIngredienteActionPerformed

    private void jc_tipoMedidaPlatoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_tipoMedidaPlatoItemStateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        //modelo = (DefaultComboBoxModel)jc_unidadMedida.getModel();
        
        String selected = jc_tipoMedidaPlato.getSelectedItem().toString();
        if(selected.equalsIgnoreCase("Volumen")){
            modelo.addElement("Litros");
            modelo.addElement("Mililitros");
            modelo.addElement("Galones");
        }
        else if(selected.equalsIgnoreCase("Masa")){
            modelo.addElement("Kilogramos");
            modelo.addElement("Libras");
            modelo.addElement("Onzas");
            modelo.addElement("Gramos");
        }
        else{
            modelo.addElement("Unidades");
        }
        jc_unidadMedidaPlato.setModel(modelo);
    }//GEN-LAST:event_jc_tipoMedidaPlatoItemStateChanged

    private void jc_cargarExistentePlatoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_cargarExistentePlatoItemStateChanged
        tf_nombreIngredientePlato.setText(jc_cargarExistentePlato.getSelectedItem().toString());
    }//GEN-LAST:event_jc_cargarExistentePlatoItemStateChanged

    private void cmd_agregarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_agregarListaActionPerformed
        if(tf_nombreIngredientePlato != null){
            String nombre = tf_nombreIngredientePlato.getText();
            double cantidad = Double.parseDouble(jsp_cantidadPlato.getValue().toString());
            String tipo = jc_tipoMedidaPlato.getSelectedItem().toString();
            String unidad = jc_unidadMedidaPlato.getSelectedItem().toString();

            Ingredient temp = new Ingredient(nombre,cantidad,unidad,tipo);
            ingredientesTemp.add(temp);

            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < storage.getAlmacen().size(); i++) {
                modelo.addElement(storage.getAlmacen().get(i).peek().getName());
            }
            for (int i = 0; i < ingredientesTemp.size(); i++) {
                modelo.addElement(ingredientesTemp.get(i).getName());
                model.addElement(ingredientesTemp.get(i).getName());
            }
            jc_cargarExistentePlato.setModel(modelo);
            jl_ingredientesPlato.setModel(model);

            tf_nombreIngredientePlato.setText("");

            JOptionPane.showMessageDialog(jd_platos, "¡Ingrediente agregado con éxito!", "¡Bien hecho!", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(jd_platos, "Nombre vacío", "Campo faltante", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmd_agregarListaActionPerformed

    private void cmd_agregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_agregarPlatoActionPerformed
        if (tf_nombrePlato != null && jl_ingredientesPlato != null) {
            String nombre = tf_nombrePlato.getText();
            double precio = Double.parseDouble(jsp_precioPlato.getValue().toString());
            int tiempo = Integer.parseInt(jsp_tiempo.getValue().toString());
            
            Plato temp = new Plato(nombre, precio, tiempo, ingredientesTemp);
            menu.add(temp);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < menu.size(); i++) {
                modelo.addElement(menu.get(i).getNombre());
            }
            jc_cargarPlato.setModel(modelo);
            ingredientesTemp = new ArrayList();
            DefaultListModel model = new DefaultListModel();
            jl_ingredientesPlato.setModel(model);
            tf_nombrePlato.setText("");
        }
    }//GEN-LAST:event_cmd_agregarPlatoActionPerformed

    private void jl_ingredientesPlatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_ingredientesPlatoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DELETE || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            int index = jl_ingredientesPlato.getSelectedIndex();
            if (index!=-1){
                DefaultListModel modelo = (DefaultListModel)jl_ingredientesPlato.getModel();
                modelo.remove(index);
                ingredientesTemp.remove(index);
                jl_ingredientesPlato.setModel(modelo);   
            }else{
                JOptionPane.showMessageDialog(this, "Por favor seleccione un elemento de la lista", "Error", JOptionPane.ERROR_MESSAGE);
            }                
        }
    }//GEN-LAST:event_jl_ingredientesPlatoKeyPressed

    private void jc_tipoMedidaPlato1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_tipoMedidaPlato1ItemStateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        //modelo = (DefaultComboBoxModel)jc_unidadMedida.getModel();
        
        String selected = jc_tipoMedidaPlato1.getSelectedItem().toString();
        if(selected.equalsIgnoreCase("Volumen")){
            modelo.addElement("Litros");
            modelo.addElement("Mililitros");
            modelo.addElement("Galones");
        }
        else if(selected.equalsIgnoreCase("Masa")){
            modelo.addElement("Kilogramos");
            modelo.addElement("Libras");
            modelo.addElement("Onzas");
            modelo.addElement("Gramos");
        }
        else{
            modelo.addElement("Unidades");
        }
        jc_unidadMedidaPlato1.setModel(modelo);
    }//GEN-LAST:event_jc_tipoMedidaPlato1ItemStateChanged

    private void jc_cargarExistentePlato1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_cargarExistentePlato1ItemStateChanged
        tf_nombreIngredientePlato1.setText(jc_cargarExistentePlato1.getSelectedItem().toString());
    }//GEN-LAST:event_jc_cargarExistentePlato1ItemStateChanged

    private void cmd_agregarLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_agregarLista1ActionPerformed
        if(tf_nombreIngredientePlato1 != null){
            String nombre = tf_nombreIngredientePlato1.getText();
            double cantidad = Double.parseDouble(jsp_cantidadPlato1.getValue().toString());
            String tipo = jc_tipoMedidaPlato1.getSelectedItem().toString();
            String unidad = jc_unidadMedidaPlato1.getSelectedItem().toString();

            Ingredient temp = new Ingredient(nombre,cantidad,unidad,tipo);
            ingredientesTemp.add(temp);

            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < storage.getAlmacen().size(); i++) {
                modelo.addElement(storage.getAlmacen().get(i).peek().getName());
            }
            for (int i = 0; i < ingredientesTemp.size(); i++) {
                modelo.addElement(ingredientesTemp.get(i).getName());
                model.addElement(ingredientesTemp.get(i).getName());
            }
            jc_cargarExistentePlato1.setModel(modelo);
            jl_ingredientesPlato.setModel(model);
            tf_nombreIngredientePlato1.setText("");

            JOptionPane.showMessageDialog(jd_platos, "¡Ingrediente agregado con éxito!", "¡Bien hecho!", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(jd_platos, "Nombre vacío", "Campo faltante", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmd_agregarLista1ActionPerformed

    private void jl_ingredientesPlato1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_ingredientesPlato1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DELETE || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            int index = jl_ingredientesPlato1.getSelectedIndex();
            if (index!=-1){
                DefaultListModel modelo = (DefaultListModel)jl_ingredientesPlato1.getModel();
                modelo.remove(index);
                ingredientesTemp.remove(index);
                jl_ingredientesPlato1.setModel(modelo);   
            }else{
                JOptionPane.showMessageDialog(this, "Por favor seleccione un elemento de la lista", "Error", JOptionPane.ERROR_MESSAGE);
            }                
        }
    }//GEN-LAST:event_jl_ingredientesPlato1KeyPressed

    private void cmd_agregarPlato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_agregarPlato1ActionPerformed
        if (tf_nombrePlato1 != null && jl_ingredientesPlato1 != null) {
            String nombre = tf_nombrePlato1.getText();
            double precio = Double.parseDouble(jsp_precioPlato1.getValue().toString());
            int tiempo = Integer.parseInt(jsp_tiempo1.getValue().toString());
            
            Plato temp = new Plato(nombre, precio, tiempo, ingredientesTemp);
            menu.set(indexModificar,temp);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < menu.size(); i++) {
                modelo.addElement(menu.get(i).getNombre());
            }
            jc_cargarPlato.setModel(modelo);
            ingredientesTemp = new ArrayList();
            DefaultListModel model = new DefaultListModel();
            jl_ingredientesPlato1.setModel(model);
            tf_nombrePlato1.setText("");
        }
    }//GEN-LAST:event_cmd_agregarPlato1ActionPerformed

    private void jc_cargarPlatoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_cargarPlatoItemStateChanged
        int indice = jc_cargarPlato.getSelectedIndex();
        tf_nombrePlato1.setText(menu.get(indice).getNombre());
        jsp_precioPlato1.setValue(menu.get(indice).getPrice());
        jsp_tiempo1.setValue(menu.get(indice).getCoccion());
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < menu.get(indice).getIngredientes().size(); i++) {
            modelo.addElement(menu.get(indice).getIngredientes().get(i).getName());
        }
        jl_ingredientesPlato1.setModel(modelo);
    }//GEN-LAST:event_jc_cargarPlatoItemStateChanged

    private void cmd_eliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_eliminarPlatoActionPerformed
        menu.remove(jc_eliminarPlato.getSelectedIndex());
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < menu.size(); i++) {
            modelo.addElement(menu.get(i).getNombre());
        }
        jc_eliminarPlato.setModel(modelo);
    }//GEN-LAST:event_cmd_eliminarPlatoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int vertices = Integer.parseInt(jsp_vertex.getValue().toString());
        grafo.addNVertices(vertices);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < grafo.getNumberOfVertices(); i++) {
            modelo.addElement(i);
        }
        jc_from.setModel(modelo);
        jc_to.setModel(modelo);
        jc_dirección.setModel(modelo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int peso = Integer.parseInt(jsp_peso.getValue().toString());
        int from = jc_from.getSelectedIndex();
        int to = jc_to.getSelectedIndex();
        boolean dirigido = isDrigida.isSelected();
        
        NumericalProperty wp = grafo.getEdgeWidthProperty();
        wp.setValue(to, peso);
        grafo.addSimpleEdge(from, to, dirigido);
        grafo.setEdgesWidth(wp);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int direccion = jc_dirección.getSelectedIndex();
        String owner = tf_cliente.getText();
        Orden orden = new Orden(direccion,owner,temp);
        ordenestotal.add(orden);
        cola.add(orden);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        int index = this.jc_menu.getSelectedIndex();
        DefaultListModel modelo = (DefaultListModel)jl_platosOrden.getModel();
        modelo.addElement(menu.get(index));
        temp.add(menu.get(index));
    }//GEN-LAST:event_btn_addActionPerformed

    private void jl_platosOrdenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_platosOrdenKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DELETE || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            int index = jl_platosOrden.getSelectedIndex();
            if (index!=-1){
                DefaultListModel modelo = (DefaultListModel)jl_platosOrden.getModel();
                modelo.remove(index);
                temp.remove(index);
                jl_platosOrden.setModel(modelo);   
            }else{
                JOptionPane.showMessageDialog(this, "Por favor seleccione un elemento de la lista", "Error", JOptionPane.ERROR_MESSAGE);
            }                
        }
    }//GEN-LAST:event_jl_platosOrdenKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    private void openDialog(javax.swing.JDialog jd_ventana){
        jd_ventana.setLocationRelativeTo(this);
        jd_ventana.setModal(true);
        jd_ventana.pack();
        jd_ventana.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton cmd_agregarAlmacen;
    private javax.swing.JButton cmd_agregarLista;
    private javax.swing.JButton cmd_agregarLista1;
    private javax.swing.JButton cmd_agregarPlato;
    private javax.swing.JButton cmd_agregarPlato1;
    private javax.swing.JButton cmd_cierre;
    private javax.swing.JButton cmd_cocina;
    private javax.swing.JButton cmd_eliminarIngrediente;
    private javax.swing.JButton cmd_eliminarPlato;
    private javax.swing.JButton cmd_ingredientes;
    private javax.swing.JButton cmd_ordenes;
    private javax.swing.JButton cmd_platos;
    private javax.swing.JCheckBox isDrigida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JComboBox jc_cargarExistente;
    private javax.swing.JComboBox jc_cargarExistentePlato;
    private javax.swing.JComboBox jc_cargarExistentePlato1;
    private javax.swing.JComboBox jc_cargarPlato;
    private javax.swing.JComboBox jc_dirección;
    private javax.swing.JComboBox jc_eliminarIngrediente;
    private javax.swing.JComboBox jc_eliminarPlato;
    private javax.swing.JComboBox jc_from;
    private javax.swing.JComboBox jc_menu;
    private javax.swing.JComboBox jc_tipoMedida;
    private javax.swing.JComboBox jc_tipoMedidaPlato;
    private javax.swing.JComboBox jc_tipoMedidaPlato1;
    private javax.swing.JComboBox jc_to;
    private javax.swing.JComboBox jc_unidadMedida;
    private javax.swing.JComboBox jc_unidadMedidaPlato;
    private javax.swing.JComboBox jc_unidadMedidaPlato1;
    private javax.swing.JDialog jd_cierre;
    private javax.swing.JDialog jd_cocina;
    private javax.swing.JDialog jd_ingredientes;
    private javax.swing.JDialog jd_ordenes;
    private javax.swing.JDialog jd_platos;
    private javax.swing.JLabel jl_icon;
    private javax.swing.JList jl_ingredientesPlato;
    private javax.swing.JList jl_ingredientesPlato1;
    private javax.swing.JList jl_platosOrden;
    private javax.swing.JSpinner jsp_cantidad;
    private javax.swing.JSpinner jsp_cantidadPlato;
    private javax.swing.JSpinner jsp_cantidadPlato1;
    private javax.swing.JSpinner jsp_peso;
    private javax.swing.JSpinner jsp_precioPlato;
    private javax.swing.JSpinner jsp_precioPlato1;
    private javax.swing.JSpinner jsp_tiempo;
    private javax.swing.JSpinner jsp_tiempo1;
    private javax.swing.JSpinner jsp_vertex;
    private javax.swing.JPanel p_agregarIngrediente;
    private javax.swing.JPanel p_agregarIngrediente1;
    private javax.swing.JPanel p_agregarIngrediente2;
    private javax.swing.JPanel p_eliminarIngrediente;
    private javax.swing.JTextField tf_cliente;
    private javax.swing.JTextField tf_nombreIngrediente;
    private javax.swing.JTextField tf_nombreIngredientePlato;
    private javax.swing.JTextField tf_nombreIngredientePlato1;
    private javax.swing.JTextField tf_nombrePlato;
    private javax.swing.JTextField tf_nombrePlato1;
    // End of variables declaration//GEN-END:variables
    private Almacen storage = new Almacen();
    private ArrayList<Ingredient> ingredientesTemp= new ArrayList(); 
    private ArrayList<Plato> menu = new ArrayList();
    private int indexModificar = -1;
    private Grph grafo = new InMemoryGrph();
    private ArrayList<Orden> ordenestotal = new ArrayList();
    private PriorityQueue<Orden> cola = new PriorityQueue();
    private ArrayList<Plato> temp = new ArrayList();
}